config/routes.rb
Rails.application.routes.draw do

  post 'reactions/new'
  get 'reactions/get'
  
  get 'swipes/watch'
  get 'swipes/like'
  get 'swipes/dont_like'
  get 'swipes/watched'
  
  get 'swipes/info'
  get 'swipes/suggest_show'

  get 'sessions/remote'
  get 'sessions/after_show'  
  get 'sessions/dash'
  get 'sessions/welcome'
  get 'sessions/new'
  get 'sessions/logout'
  get 'sessions/pick_a_show'

  get "auth/failure", to: "sessions#auth_failure"
  get 'auth/facebook/callback', to: 'sessions#create'

  root "sessions#welcome" 
end

app/models/reaction.rb
class Reaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :show

  scope :text,  -> { where(reaction_type: 'text') }

end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :reactions


end

app/models/swipe.rb
class Swipe < ActiveRecord::Base
  belongs_to :user
  belongs_to :show
  STATES = %w[dislike like watched watching]

  scope :watching,  -> { where(state: 'watching') }
  scope :watched,  -> { where(state: 'watched') }
  scope :dislike,  -> { where(state: 'dislike') }
  scope :like,  -> { where(state: 'like') }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :swipes
  has_many :reactions

  def watched_shows 
    self.swipes.where(state: "watched")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include CurrentUser

end

app/controllers/concerns/current_user.rb
module CurrentUser
  extend ActiveSupport::Concern

  included do
    helper_method :current_user
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = User.find_by(id: session[:user_id])
  end

  def sign_in(user)
    user_id = user.respond_to?(:id) ? user.id : user
    session[:user_id] = user_id
  end

  def sign_out
    session[:user_id] = nil
    cookies[:auth_token] = nil
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

  def new
    reaction = Reaction.new(user_id: current_user.id, show_id: session[:show_id], reaction: params[:reaction])
    reaction.save
    render :json => reaction
  end

  def get
    reactions = Reaction.where(show_id: session[:show_id])    
    render :json => reactions
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_user, only: %i[pick_a_show dash delete after_show]


	def welcome
    redirect_to sessions_remote_path if current_user
  end

  def new
  	redirect_to "/auth/facebook"
  end

  def create
    @service = FacebookRegistrationService.new(request.env["omniauth.auth"])
    if @service.register!
      sign_in(@service.user)
      redirect_to sessions_pick_a_show_path
    else
      redirect_to root_path
    end
  end

  def pick_a_show

  end

  def logout
    sign_out
    redirect_to root_path
  end

  def dash
    @body_class = 'dash'
    @user = current_user
  end

  def after_show
    @body_class = 'after_show'
  end

  def remote
    redirect_to sessions_pick_a_show_path if new_user?
    @shows = []
    Swipe.watching.each do |s|
      @shows << Show.find(s.show_id)
    end
  end

  def auth_failure
    redirect_to root_path
  end

  private
  def new_user?
    true if Swipe.where(user_id: current_user.id).count < 0
  end

  def require_user
    redirect_to root_path if current_user.blank?
  end
end

app/controllers/swipes_controller.rb
class SwipesController < ApplicationController
  $counter = 1

  def watch
    $counter = 1
    swipe = Swipe.new
    show = Show.find(session[:show_id])
    swipe.update_attributes(user_id: current_user.id, show_id: show.id, state: "watching")
  end

  def like
    swipe = Swipe.new
    show = Show.find(session[:show_id])
    swipe.update_attributes(user_id: current_user.id, show_id: show.id, state: "like")
    suggest_show
  end

  def dont_like
    swipe = Swipe.new
    show = Show.find(session[:show_id])
    swipe.update_attributes(user_id: current_user.id, show_id: show.id, state: "dislike")
    suggest_show
  end

  def watched
    swipe = Swipe.new
    show = Show.find(session[:show_id])
    swipe.update_attributes(user_id: current_user.id, show_id: show.id, state: "watched")
    suggest_show
  end

  def info
    @show = Show.find(session[:show_id])
  end

  def suggest_show
    show = Show.find($counter) 
    $counter =  $counter + 1
    reaction = show.reactions.text.first
    show.img_link = ActionController::Base.helpers.image_url("gifs/#{show.img_link}")
    session[:show_id] = show.id
    render :json => {:show => show, :reaction => reaction, :reaction_author => User.find(reaction.user_id) }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/swipes_helper.rb
module SwipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PomDeCouch</title>
 	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,500' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= "#{@body_class}".strip %>">
<div class="container phone-window" >
<%= yield %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/reactions/list_reactions.html.erb
<div class="chat-window">
  <div class="chat-messages">
    <ol class="chat-messages-list">
      <% @reactions.each do |r| %>
        <li class="chat-message chat-message-friend">
          <div class="chat-message-bubble">
            <%= r.reaction %> <i><%= User.find(r.user_id).name %></i> 
          </div>
        </li>
      <% end %>
    </ol>
  </div>
  <div class="chat-input-bar">
    <div class="chat-info-container">

    </div>
    <div class="chat-effect-container">
      <div class="chat-effect-bar"></div>
    </div>
    <div class="chat-input-wrapper">
      <button class="chat-input-tool">
        <i class="icon icon-camera"></i>
      </button>
      <div class="chat-input" id="submitReaction" contenteditable>
        

      </div>
      <button class="chat-send">
        <i class="fa fa-paper-plane"></i>
      </button>
    </div>
  </div>
</div>




<br/><br/>
<form>
Reaction:<br>
<input type="text" name="reaction">
<br>
<button id="submitReaction">Submit</button>
</form>

<script type="text/javascript">
  var new_reaction_url = '<%= url_for(reactions_new_path) %>';
</script>

app/views/swipes/info.html.erb
<h1><%= @show.title %></h1>
<h3>Duration: <%= @show.duration %> </h3>
<h3>Rating: <%= @show.rating %> / 5 </h3>
<%= link_to "Back", sessions_dash_path %>

app/views/swipes/watch.html.erb
<div class="col-xs-12 RecTitle">
	<h1>Recording...</h1>
</div>
<div class="audioWave">
	<%= image_tag "audioWaves.svg", :class => "audioWaveIcn"   %>
</div>
<div class="col-xs-12 save">
	<%= link_to sessions_after_show_path do %>
		<%= image_tag "save.svg", :class => "saveIcn"   %>
	<% end %>
</div>